DEF QUERY qry2 FOR invoice .
    DEF BROWSE b2 QUERY qry2 NO-LOCK
        DISP invoicenum invoicedate totalpaid 
        WITH 15 DOWN MULTIPLE WIDTH 40 TITLE "Customer list".
DEF FRAME f2 b2 WITH SIDE-LABELS AT ROW 2 COLUMN 10 .
DEF QUERY qry FOR customer.
    DEF BROWSE b QUERY qry NO-LOCK
        DISP customer.custnum COLUMN-BGCOLOR 007 customer.NAME COLUMN-BGCOLOR 009 
        WITH 15 DOWN MULTIPLE WIDTH 40 TITLE "Customer list".
DEF FRAME f b WITH SIDE-LABELS AT ROW 2 COLUMN 2 .
ON VALUE-CHANGED OF b
DO:
  OPEN QUERY qry2 FOR EACH invoice OF customer  NO-LOCK.
    ENABLE b2 WITH FRAME f2.
    WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
END.
      

OPEN QUERY qry FOR EACH customer NO-LOCK.
    ENABLE b WITH FRAME f.
    WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.

