DEF QUERY qry FOR customer.
    DEF BROWSE b QUERY qry NO-LOCK
        DISP custnum COLUMN-BGCOLOR 007 NAME COLUMN-BGCOLOR 009 
        WITH 15 DOWN MULTIPLE WIDTH 40 TITLE "Customer list".
DEF FRAME f b WITH SIDE-LABELS AT ROW 2 COLUMN 2 .
ON VALUE-CHANGED OF b
      MESSAGE "value changed" VIEW-AS ALERT-BOX.

OPEN QUERY qry FOR EACH customer NO-LOCK.
    ENABLE b WITH FRAME f.
    WAIT-FOR WINDOW-CLOSE OF CURRENT-WINDOW.
