
DEF VAR v-cnt     AS CHARACTER NO-UNDO INIT 'Pro'.
DEF VAR v-cnt-out AS CHARACTER NO-UNDO.


RUN p-calculate(INPUT v-cnt)NO-ERROR.
IF ERROR-STATUS:ERROR THEN
MESSAGE RETURN-VALUE VIEW-AS ALERT-BOX.

PROCEDURE p-calculate:
    DEF INPUT parameter v-cnt1 AS CHARACTER NO-UNDO.
     RETURN ERROR (v-cnt1 + 'Gress'). 
    /*RETURN. */
END PROCEDURE.
