DEF VAR v-cnt AS INTEGER NO-UNDO.
DEF VAR hvalue AS HANDLE NO-UNDO.

FUNCTION f-demo RETURNS INT (INPUT p-cnt AS INTEGER ) IN hvalue.

RUN 'D:\niranjan\Block 1\060\8.p' PERSISTENT SET hvalue.
DO v-cnt = 1 TO 3.
 MESSAGE f-demo(v-cnt) VIEW-AS ALERT-BOX.
 MESSAGE hvalue:INTERNAL-ENTRIES VIEW-AS ALERT-BOX.
END.
