DEFINE VARIABLE func AS CHARACTER  NO-UNDO.
FUNCTION getgreeting RETURNS CHARACTER FORWARD.
FUNCTION getInteger RETURNS INTEGER FORWARD.
FUNCTION getLogical RETURNS LOGICAL FORWARD.
ASSIGN
    func = "getgreeting".
MESSAGE DYNAMIC-FUNCTION(func IN THIS-PROCEDURE)
    VIEW-AS ALERT-BOX INFO BUTTONS OK.
FUNCTION getgreeting RETURNS CHARACTER.
RETURN "Hello".
END.


